# Baed on https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Multiple Platform IRLC Build

on:
  push:
    branches: [ "main", "software" ]
  pull_request:
    branches: [ "main", "software" ]

env:
  CPM_SOURCE_CACHE: ~/cpm-cache

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - os: windows-latest
            build_type: Release
            c_compiler: msvc
            cxx: msvc

          - os: ubuntu-latest
            c_compiler: gcc
            cxx: g++

          - os: ubuntu-latest
            c_compiler: clang
            cxx: clang++

          - os: macos-latest
            c_compiler: clang
            cxx: clang++

        exclude:
          - os: macos-latest
            c_compiler: gcc

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "source-dir=${{ github.workspace }}/software/irlc" >> "$GITHUB_OUTPUT"
        echo "build-output-dir=${{ github.workspace }}/software/irlc/build/" >> "$GITHUB_OUTPUT"
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          echo "build-exe-subdir=${{ matrix.build_type }}/" >> "$GITHUB_OUTPUT"
          echo "exe-suffix=.exe" >> "$GITHUB_OUTPUT"
        else
          echo "build-exe-subdir=" >> "$GITHUB_OUTPUT"
          echo "exe-suffix=" >> "$GITHUB_OUTPUT"
        fi

    # First, cache downloaded deps
    - name: Set up cache
      id: cache-cpm
      uses: actions/cache@v4
      with:
        path: ~/cpm-cache
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-

    # Now we get ccache
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        -S ${{ steps.strings.outputs.source-dir }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: >
        cmake --build ${{ steps.strings.outputs.build-output-dir }}
        --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: irlc-${{ matrix.os }}-${{ matrix.c_compiler }}
        path: ${{ steps.strings.outputs.build-output-dir }}/${{ steps.strings.outputs.build-exe-subdir }}irlc${{ steps.strings.outputs.exe-suffix }}
